import type { PlanningDebugRecord, PlanningSnapshot } from "@/lib/core/types";
import { DebugBlock } from "@/components/ui/debug-block";
import { PageHeader } from "@/components/ui/page-header";
import { SectionCard } from "@/components/ui/section-card";

type Props = {
  todaySnapshot: PlanningSnapshot | null;
  weekSnapshot: PlanningSnapshot | null;
  todayDebug: PlanningDebugRecord | null;
  weekDebug: PlanningDebugRecord | null;
};

export function DebugPanel({ todaySnapshot, weekSnapshot, todayDebug, weekDebug }: Props) {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Debug"
        description="Raw planner artifacts for validating ranking output, provider ingestion, and recent debug traces."
      />
      <SectionCard
        title="Planner artifacts"
        description="Latest persisted JSON payloads from `/today`, `/week`, and their associated debug traces."
      >
        <div className="grid gap-4 xl:grid-cols-2">
          <SnapshotCard title="Latest /today snapshot" payload={todaySnapshot} />
          <SnapshotCard title="Latest /week snapshot" payload={weekSnapshot} />
          <SnapshotCard title="Latest /today debug trace" payload={todayDebug} />
          <SnapshotCard title="Latest /week debug trace" payload={weekDebug} />
        </div>
      </SectionCard>
    </div>
  );
}

function SnapshotCard({ title, payload }: { title: string; payload: PlanningSnapshot | PlanningDebugRecord | null }) {
  return <DebugBlock title={title} payload={payload} description="Stored exactly as generated by the planner service." />;
}
